name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml

  upload-release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-windows-*
          path: dist
          merge-multiple: true

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 